region: "us-west-2"
identifier: "rag-app"
tags:
  Workspace: "IaC/lambda"

role_arn: "arn:aws:iam::580118073904:role/TerraformRole"

s3:
  name: "landing-zone"
  bucketNamespace: "account-regional"
  lambdaTrigger: false

sqs:
  name: "ingestion"

dynamoDB:
  tableName: "documents"

bedrock:
  inferenceProfileId: "us.amazon.nova-pro-v1:0"
  dataAutomationProjectId: "3582b7d2b55a"
  dataAutomationProfileId: "us.data-automation-v1"

lambdaLayer:
  enabled: false
  fileName: "dependencies.zip"
  compatibleRuntimes:
   - "nodejs24.x"
   - "python3.12"
  compatibleArchitectures:
   - "x86_64"
   - "arm64"


lambda:
  dataUpload:
    functionName: "data-upload"
    role: "dataUpload"
    sourceCodePath: "data_upload/"
    outputCodePath: "data_upload/function.zip"
    handler: "handler.lambda_handler"
    runtime: "python3.13"
    timeout: 30
    vpcConfig: false
    lambdaLayer: 
      enabled: false
    eventSourceMapping:
      enabled: false
  dataProcessor:
    functionName: "data-processor"
    role: "dataProcessor"
    sourceCodePath: "data_processor/"
    outputCodePath: "data_processor/function.zip"
    handler: "handler.lambda_handler"
    runtime: "python3.13"
    timeout: 60
    vpcConfig: false
    lambdaLayer:
      enabled: false
    eventSourceMapping:
      enabled: true
      type: "sqs"
      name: "ingestion"
  retrieveAndGenerate:
    functionName: "retrieve-and-generate"
    role: "retrieveAndGenerate"
    sourceCodePath: "retrieve_and_generate/"
    outputCodePath: "retrieve_and_generate/function.zip"
    handler: "handler.lambda_handler"
    runtime: "python3.13"
    timeout: 120
    memorySize: 512
    vpcConfig: false
    lambdaLayer:
      enabled: true
      arns:
        - "arn:aws:lambda:us-west-2:856699698935:layer:strands-agents-py3_13-x86_64:2"
    eventSourceMapping:
      enabled: false
  ingestionPostProcessor:
    functionName: "ingestion-post-processor"
    role: "ingestionPostProcessor"
    sourceCodePath: "ingestion_post_processor/"
    outputCodePath: "ingestion_post_processor/function.zip"
    handler: "handler.lambda_handler"
    runtime: "python3.13"
    timeout: 30
    vpcConfig: false
    lambdaLayer:
      enabled: false
    eventSourceMapping:
      enabled: false
  agentRiskClause:
    functionName: "agent-risk-clause"
    role: "agentRiskClause"
    sourceCodePath: "agent_risk_clause/"
    outputCodePath: "agent_risk_clause/function.zip"
    handler: "handler.lambda_handler"
    runtime: "python3.13"
    timeout: 300
    memorySize: 512
    vpcConfig: false
    lambdaLayer:
      enabled: false
    eventSourceMapping:
      enabled: false
  agentTemplatePrepopulation:
    functionName: "agent-template-prepopulation"
    role: "agentTemplatePrepopulation"
    sourceCodePath: "agent_template_prepopulation/"
    outputCodePath: "agent_template_prepopulation/function.zip"
    handler: "handler.lambda_handler"
    runtime: "python3.13"
    timeout: 300
    memorySize: 512
    vpcConfig: false
    lambdaLayer:
      enabled: false
    eventSourceMapping:
      enabled: false
  documentExtraction:
    functionName: "document-extraction"
    role: "documentExtraction"
    sourceCodePath: "document_extraction/"
    outputCodePath: "document_extraction/function.zip"
    handler: "handler.lambda_handler"
    runtime: "python3.13"
    timeout: 300
    memorySize: 256
    vpcConfig: false
    lambdaLayer:
      enabled: false
    eventSourceMapping:
      enabled: true
      type: "sqs"
      name: "document-extraction"
  signatureWorkflow:
    functionName: "signature-workflow"
    role: "signatureWorkflow"
    sourceCodePath: "signature_workflow/"
    outputCodePath: "signature_workflow/function.zip"
    handler: "handler.lambda_handler"
    runtime: "python3.13"
    timeout: 30
    vpcConfig: false
    lambdaLayer:
      enabled: false
    eventSourceMapping:
      enabled: false
  agentSummary:
    functionName: "agent-summary"
    role: "agentSummary"
    sourceCodePath: "agent_summary/"
    outputCodePath: "agent_summary/function.zip"
    handler: "handler.lambda_handler"
    runtime: "python3.13"
    timeout: 300
    memorySize: 512
    vpcConfig: false
    lambdaLayer:
      enabled: false
    eventSourceMapping:
      enabled: false