region: "us-east-1"
identifier: "rag-app"
tags: 
  Workspace: "IaC/ses"

role_arn: "arn:aws:iam::580118073904:role/TerraformRole"

ses: 
  hostedZone: "judy.ai"
  privateZone: false
  configurationSet:
    notifications:
      name: "my-first-configuration-set"
      sendingEnabled: true
  templates:
    welcome:
      name: "welcomeTemplate"
      subject: "Welcome aboard {{name}}!"
      htmlPath: "templates/welcome.html"

