region: "us-west-2"
identifier: "rag-app"
tags: 
  Workspace: "IaC/api-gateway"

role_arn: "arn:aws:iam::580118073904:role/TerraformRole"

cloudfrontDomain: 
  name: "judyai"

s3:
  name: "website"
  bucketNamespace: "account-regional"

apiGateway:
  lambdaGateway:
    name: "api"
    description: "REST API for RAG application"
    protocolType: "HTTP"
    #hostedZoneName: "test.judy.ai"
    #domainName: "api.test.judy.ai"
    #certificateDomainName: "*.test.judy.ai"
    authorizer:
      enabled: true
      name: "cognito"
      userPool: "pool"
    corsConfiguration:
      allow_headers:
        - "content-type"
        - "x-amz-date"
        - "authorization"
        - "x-api-key"
        - "x-amz-security-token"
        - "x-amz-user-agent"
      allow_methods:
        - "*"
      allow_origins:
        - "*"
    lambdaFunctions:
      dataUploadPost:
        functionName: "data-upload"
        path: "/upload"
        method: "POST"
        integrationMethod: "POST"
        authRequired: true
        timeoutMilliseconds: 29000
      chatPost:
        functionName: "retrieve-and-generate"
        path: "/chat"
        method: "POST"
        integrationMethod: "POST"
        authRequired: true
        timeoutMilliseconds: 29000
      filesGet:
        functionName: "data-processor"
        path: "/files"
        method: "GET"
        integrationMethod: "POST"
        authRequired: true
        timeoutMilliseconds: 29000
      filesDocumentIdDelete:
        functionName: "data-processor"
        path: "/files/{documentId}"
        method: "DELETE"
        integrationMethod: "POST"
        authRequired: true
        timeoutMilliseconds: 29000
      contractsRoutePost:
        functionName: "signature-workflow"
        path: "/contracts/{contractId}/route"
        method: "POST"
        integrationMethod: "POST"
        authRequired: true
        timeoutMilliseconds: 29000
      contractsSignersGet:
        functionName: "signature-workflow"
        path: "/contracts/{contractId}/signers"
        method: "GET"
        integrationMethod: "GET"
        authRequired: true
        timeoutMilliseconds: 29000
      contractsSignPost:
        functionName: "signature-workflow"
        path: "/contracts/{contractId}/sign"
        method: "POST"
        integrationMethod: "POST"
        authRequired: true
        timeoutMilliseconds: 29000
      contractsAnalysisPost:
        functionName: "analysis-api"
        path: "/contracts/{contractId}/analysis"
        method: "POST"
        integrationMethod: "POST"
        authRequired: true
        timeoutMilliseconds: 29000
      contractsAnalysisGet:
        functionName: "analysis-api"
        path: "/contracts/{contractId}/analysis"
        method: "GET"
        integrationMethod: "GET"
        authRequired: true
        timeoutMilliseconds: 29000
      contractsAnalysisByAgentTypeGet:
        functionName: "analysis-api"
        path: "/contracts/{contractId}/analysis/{agentType}"
        method: "GET"
        integrationMethod: "GET"
        authRequired: true
        timeoutMilliseconds: 29000
    